--  1. 이름이 없는 동물의 아이디 코드를 입력하세요

       SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NULL

-- 2. 이름이 있는 동물의 아이디 코드를 입력하세요

      SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL ORDER BY ANIMAL_ID
      
-- 3. NULL 처리하기 코드를 입력하세요
-- NULL이라면 No Name 으로 출력 -> IFNULL(컬럼명, NULL 시 값);

      SELECT ANIMAL_TYPE,IFNULL(NAME,"No name"),SEX_UPON_INTAKE FROM ANIMAL_INS ORDER BY ANIMAL_ID
      
-- 4. 없어진 기록 찾기 코드를 입력하세요
-- ANIMAL_OUTS 와 ANIMAL_INS 를 ANIMAL_ID가 같은 것을 기준으로 LEFT OUTER JOIN 
-- ANIMAL_ID가 같은 값이 ANIMAL_INS 테이블에 존재하지 않는다면, NULL 값

      SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME FROM ANIMAL_OUTS
      LEFT OUTER JOIN ANIMAL_INS on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
      WHERE ANIMAL_INS.ANIMAL_ID IS NULL
      ORDER BY ANIMAL_OUTS.ANIMAL_ID
  
  -- ANIMAL_OUTS OUTS , ANIMAL_INS INS 로 정리하면 다음과 같이 작성할 수 있다.
/*
      SELECT OUTS.ANIMAL_ID, OUTS.NAME
      FROM ANIMAL_OUTS OUTS
      LEFT OUTER JOIN ANIMAL_INS INS
      ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
      WHERE INS.ANIMAL_ID is NULL
      ORDER BY OUTS.ANIMAL_ID
*/
